### ISSUE TITLE
Tracking issue for v0.12.0 release

### ISSUE THREAD

**Issue by Carter12s** [RosLibRust/roslibrust#217]
This release is unusually large, and trying to keep some of the details and follow on items tracked here.

May turn several of these into issues, and convert this into a milestone, but for now just keeping notes here.

- [x] Re-write several of the READMEs now that roslibrust_rosbridge isn't the primary purpose and instead just a backend option. How the crate is advertised should shift.
- [x] Update documentation / examples to highlight using Traits and swapping in backends
- [x] Establish new release procedures, and versioning on the crates. I think we're ready to start tracking independent versions of each crate, and releasing one at a time instead of keeping a synced version for everything.
- [x] We should do some marketing / announcements / blog posts about the new features

**Comment by Carter12s** [comment]
Made good progress on cleanups code is probably in a good enough state now to publish.
